# Reusable workflow for building and deploying the website
# https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
name: Build And Deploy

on:
  workflow_call:
    inputs:
      branch:
        description: 'If we are in "main" or a "version" docs branch'
        required: true
        type: string
    secrets:
      SAS:
        required: true

jobs:
  build_and_deploy:
    name: Build and deploy the website
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Set GIT_BRANCH
        run: echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Print GIT_BRANCH
        run: echo $GIT_BRANCH
      - name: Print content
        run: ls -ln
      - name: Print branch if version
        if: ${{ inputs.branch == 'version' }}
        run: echo ${{ inputs.branch }}
      - name: Print branch if main
        if: ${{ inputs.branch == 'main' }}
        run: echo ${{ inputs.branch }}
      # This should be set up from earlier
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag: v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # tag: v4.0.3
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # tag: v1.10.2
      - name: Lint
        run: yarn lint
        env:
          CI: true
      # FIXME: this is stalling
      # - name: Download cache
      #   uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e  # tag: v3.0.0
      #   with:
      #     timeout_seconds: 300
      #     max_attempts: 3
      #     retry_on: error
      #     command: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
      #   env:
      #     SAS: ${{ secrets.SAS }}
      - name: Rewrite docs paths if version branch
        if: ${{ inputs.branch == 'version' }}
        run: node scripts/build-as-doc-version.js $(GIT_BRANCH)
      - name: Add Docusaurus problem matcher
        run: echo "::add-matcher::.github/problem-matchers/docusaurus.json"
      - name: Build default locale site
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish "/assets" to Storage if version branch
        if: ${{ inputs.branch == 'version' }}
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # tag: v3.0.0
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/assets/*" "https://electronwebsite.blob.core.windows.net/%24web/assets?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
      - name: Publish "/docs" to Storage if version branch
        if: ${{ inputs.branch == 'version' }}
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # tag: v3.0.0
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/docs/*" "https://electronwebsite.blob.core.windows.net/%24web/docs?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
      - name: Publish everything to Storage if main branch
        if: ${{ inputs.branch == 'main' }}
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # tag: v3.0.0
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web/?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
