name: Check Blog Links

on:
  pull_request:
    branches:
      - main
    paths:
      - blog/*.md

jobs:
  check-blog-links:
    name: Check Blog Links
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Setup Node.js
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: yarn install
      - name: Check for changed blog posts
        id: check-for-changed-blog-posts
        uses: tj-actions/changed-files@40853de9f8ce2d6cfdc73c1b96f14e22ba44aec4 # v45.0.0
        with:
          files: blog/*.md
      - name: Check blog post links
        if: steps.check-for-changed-blog-posts.outputs.any_changed == 'true'
        run: npx lint-roller-markdown-links --ignore-path .markdownlintignore --fetch-external-links ${{ steps.check-for-changed-blog-posts.outputs.all_changed_files }}
