name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag: v3.3.0

      - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # tag: v3.6.0
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@d476752204653fb5cce6c09db0eaf220761f5d9e # tag: v1.8.37

      - name: Test
        run: yarn lint && yarn test
        env:
          CI: true
