name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # tag: v4.2.0

      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # tag: v4.0.4
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # tag: v1.10.2

      - name: Lint
        run: yarn lint
        env:
          CI: true
