name: Pull request

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4.2.2

      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # tag: v4.1.0
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@438a933ce1059e4e2b39e3d2a42c5067070dd444 # tag: v1.10.4

      - name: Lint
        run: yarn lint
        env:
          CI: true
