name: Push and publish main

on:
  push:
    branches:
      - main

jobs:
  # Make a reusable workflow
  crowdin-upload:
    name: Upload to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # tag: v3.3.0
      - name: Use Node.js 16
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # tag: v3.6.0
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@8add8c6d2c8586964896d9fdc639e021312a643f # tag: v1.8.28
      - name: Upload sources to Crowdin
        run: 'yarn i18n:upload'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  build-and-deploy:
    uses: electron/website/.github/workflows/build-and-deploy.yml@main
    with:
      branch: main
    secrets:
      SAS: ${{ secrets.SAS }}
