name: Push and publish main

on:
  schedule:
    # twice a day at midnight and noon
    - cron: '0 0,12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: publish

jobs:
  # Make a reusable workflow
  crowdin-upload:
    name: Upload to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4.2.2
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # tag: v4.0.4
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@dc9579d3dfb9c0e7a1f56c194eefcb8e2c9f0da5 # tag: v1.10.3
      - name: Upload sources to Crowdin
        run: 'yarn i18n:upload'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  build-and-deploy:
    name: Build and deploy the website
    runs-on: ubuntu-latest
    permissions:
      actions: read
    steps:
      - name: Set GIT_BRANCH
        run: echo "GIT_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - name: Print GIT_BRANCH
        run: echo $GIT_BRANCH
      - name: Print content
        run: ls -ln
      # This should be set up from earlier
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # tag: v4.2.2
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # tag: v4.0.4
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@dc9579d3dfb9c0e7a1f56c194eefcb8e2c9f0da5 # tag: v1.10.3
      - name: Lint
        run: yarn lint
        env:
          CI: true
      # FIXME: this is stalling
      # - name: Download cache
      #   uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e  # tag: v3.0.0
      #   with:
      #     timeout_seconds: 300
      #     max_attempts: 3
      #     retry_on: error
      #     command: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
      #   env:
      #     SAS: ${{ secrets.SAS }}
      - name: Add Docusaurus problem matcher
        run: echo "::add-matcher::.github/problem-matchers/docusaurus.json"
      - name: Build default locale site
        run: yarn build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish everything to Storage
        uses: nick-invision/retry@7152eba30c6575329ac0576536151aca5a72780e # tag: v3.0.0
        with:
          timeout_seconds: 300
          max_attempts: 3
          retry_on: error
          command: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web/?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
