name: Push and publish main

on:
  push:
    branches:
      - main

jobs:
  # Make a reusable workflow
  crowdin-upload:
    name: Upload to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        uses: bahmutov/npm-install@HEAD
      - name: Upload sources to Crowdin
        run: 'yarn i18n:upload'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  build-and-deploy:
    uses: electron/website/.github/workflows/build-and-deploy.yml@main
    with:
      branch: main
    secrets:
      SAS: ${{ secrets.SAS }}
