name: Push and publish main

on:
  schedule:
    # twice a day at midnight and noon
    - cron: '0 0,12 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: publish

jobs:
  # Make a reusable workflow
  crowdin-upload:
    name: Upload to Crowdin
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag: v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # tag: v4.0.3
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # tag: v1.10.2
      - name: Upload sources to Crowdin
        run: 'yarn i18n:upload'
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

  build-and-deploy:
    uses: electron/website/.github/workflows/build-and-deploy.yml@main
    permissions:
      actions: read
    with:
      branch: main
    secrets:
      SAS: ${{ secrets.SAS }}
