name: 'Update i18n deploy'

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  deploy:
    name: 'Build and deploy localized site'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        uses: bahmutov/npm-install@HEAD

      - name: Download crowdin translation
        run: yarn i18n:download
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Update Crowdin glossary
        run: yarn i18n:glossary
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Download cache
        run: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
        env:
          SAS: ${{ secrets.SAS }}

      - name: Build
        run: yarn i18n:build

      - name: Deploy
        run: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
