name: Update Governance Page Data

on:
  schedule:
  - cron: '0 13 * * 1'

jobs:
  governance:
    name: Updates
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3.3.0
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3.6.0
      with:
        node-version: 16
    - name: Install dependencies
      run: 'yarn'
    - name: Update governance data and push
      run: 'yarn governance'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
