name: 'Update i18n deploy'

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    name: 'Build and deploy localized site'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag: v4.1.7

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # tag: v4.0.3
        with:
          node-version: 20

      - name: Install dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # tag: v1.10.2

      - name: Download crowdin translation
        run: yarn i18n:download
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      - name: Update Crowdin glossary
        run: yarn i18n:glossary
        env:
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # TODO: figure out if this can be re-enabled?
      # - name: Download cache
      #   run: ./scripts/bin/azcopy copy "https://electronwebsite.blob.core.windows.net/%24web/*?$SAS" "./build" --recursive
      #   env:
      #     SAS: ${{ secrets.SAS }}

      - name: Add Docusaurus problem matcher
        run: echo "::add-matcher::.github/problem-matchers/docusaurus.json"

      - name: Build
        run: yarn i18n:build

      - name: Deploy
        run: ./scripts/bin/azcopy copy "./build/*" "https://electronwebsite.blob.core.windows.net/%24web?$SAS" --recursive
        env:
          SAS: ${{ secrets.SAS }}
