name: 'Update docs'

on:
  repository_dispatch:
    types: [doc_changes]

jobs:
  update-docs:
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.branch.outputs.branch }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # tag: v4.1.2
      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # tag: v4.0.2
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@237ded403e6012a48281f4572eab0c8eafe55b3f # tag: v1.10.1
      - name: 'Prebuild'
        run: 'yarn pre-build ${{ github.event.client_payload.sha }} ${{ github.event.client_payload.branch}}'
      - name: 'Push changes or create PR'
        run: 'yarn process-docs-changes'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: branch
        run: echo "branch=$(git branch --show-current)" >> $GITHUB_OUTPUT
  # GitHub will not kick the "push-XXX" workflow so we have to publish from here
  build-and-deploy:
    needs: [update-docs]
    # If we are in the "main" branch, it means we have pushed the changed directly and should deploy
    if: ${{ needs.update-docs.outputs.branch == 'main' }}
    uses: electron/website/.github/workflows/build-and-deploy.yml@main
    with:
      branch: main
    secrets:
      SAS: ${{ secrets.SAS }}
