name: 'Update docs branch'

on:
  repository_dispatch:
    types: [doc_changes_branches]
  workflow_dispatch:
    inputs:
      branch:
        type: string
        description: The branch of the commit, usually something like `15-x-y`
        required: true
      sha:
        type: string
        description: The SHA of the `electron/electron` commit
        required: true

permissions: {}

jobs:
  update-docs:
    runs-on: ubuntu-latest
    environment: docs-updater
    steps:
      - name: Generate GitHub App token
        uses: electron/github-app-auth-action@384fd19694fe7b6dcc9a684746c6976ad78228ae # v1.1.1
        id: generate-token
        with:
          creds: ${{ secrets.DOCS_UPDATER_GH_APP_CREDS }}
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # tag: v4.1.7
        with:
          token: ${{ steps.generate-token.outputs.token }}
      - name: Switch branches
        # We switch to the version branch or create a new one if needed
        run: git fetch origin && git checkout -t origin/v${{ github.event.client_payload.branch || github.event.inputs.branch }} || git checkout -b v${{ github.event.client_payload.branch || github.event.inputs.branch }}
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # tag: v4.0.3
        with:
          node-version: 20
      - name: Install dependencies
        uses: bahmutov/npm-install@e5c7e14408aa6089501de32bd16123b41738047e # tag: v1.10.2
      - name: Prebuild
        run: |
          yarn pre-build ${{ github.event.client_payload.sha || github.event.inputs.sha }}
          git add .
      - name: Push changes
        uses: dsanders11/github-app-commit-action@5c7daabae956f8143277417996b26a173439e1b7 # v1.4.1
        with:
          message: 'chore: update ref to docs (🤖)'
          token: ${{ steps.generate-token.outputs.token }}
